services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: larago
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  sftp:
    image: atmoz/sftp:alpine
    command: ordin:ordin:::upload
    ports:
      - "2222:22"
    volumes:
      - sftpdata:/home/ordin/upload

volumes:
  pgdata:
  miniodata:
  rabbitmqdata:
  redisdata:
  sftpdata:
